version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: flowable-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Flow@2026#Db!Str0ng
      MYSQL_DATABASE: flowable_db
      MYSQL_USER: flowable
      MYSQL_PASSWORD: Flow@2026#Fable!9
    ports:
      - "3307:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --sql-mode=""
    volumes:
      - ./mysql-data:/var/lib/mysql
