-- 测试用机构表初始化 (H2 compatible)
CREATE TABLE IF NOT EXISTS sys_org (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    parent_id VARCHAR(64),
    tenant_id VARCHAR(64) NOT NULL UNIQUE,
    level INT DEFAULT 1,
    sort_order INT DEFAULT 0,
    status INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO sys_org VALUES ('ORG_001', '总公司',       NULL,       'ORG_TENANT_001', 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_org VALUES ('ORG_002', '华东分公司',   'ORG_001',  'ORG_TENANT_002', 2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_org VALUES ('ORG_003', '上海办事处',   'ORG_002',  'ORG_TENANT_003', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_org VALUES ('ORG_004', '华南分公司',   'ORG_001',  'ORG_TENANT_004', 2, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO sys_org VALUES ('ORG_005', '深圳办事处',   'ORG_004',  'ORG_TENANT_005', 3, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
